package net.perfectdreams.loritta.plugin.globalpunishmentrelaysystem.utils

enum class PunishmentCategory {
	UNKNOWN,
	RAIDING,
	ADVERTISING,
	DM_ADVERTISING,
	MISC_ADVERTISING,
	USERBOT,
	SCAMMING,
	BREAKING_DISCORD_TERMS_OF_SERVICE,
	DISCRIMINATION,
	NSFW_CONTENT,
	NSFL_CONTENT,
	HARASSMENT,
	DOXXING,
	MALICIOUS_FILES
}