files:
  - source: /en/*.yml
    translation: /%locale%/%original_file_name%
    ignore: [ "/translators.yml", "/language.yml" ]
  - source: /en/commands/*.yml
    translation: /%locale%/commands/%original_file_name%
