package com.mrpowergamerbr.loritta.frontend.views;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.jooby.Request;
import org.jooby.Response;

import com.mitchellbosecke.pebble.error.PebbleException;
import com.mitchellbosecke.pebble.template.PebbleTemplate;
import com.mrpowergamerbr.loritta.LorittaLauncher;
import com.mrpowergamerbr.loritta.commands.CommandBase;
import com.mrpowergamerbr.loritta.commands.CommandOptions;
import com.mrpowergamerbr.loritta.commands.vanilla.fun.TristeRealidadeCommand;
import com.mrpowergamerbr.loritta.commands.vanilla.fun.TristeRealidadeCommand.TristeRealidadeCommandOptions;
import com.mrpowergamerbr.loritta.frontend.LorittaWebsite;
import com.mrpowergamerbr.loritta.frontend.utils.RenderWrapper;
import com.mrpowergamerbr.loritta.userdata.JoinLeaveConfig;
import com.mrpowergamerbr.loritta.userdata.ServerConfig;
import com.mrpowergamerbr.temmiediscordauth.TemmieDiscordAuth;
import com.mrpowergamerbr.temmiediscordauth.utils.TemmieGuild;

public class ConfigureServerView {

	public static Object render(Request req, Response res, TemmieDiscordAuth temmie, String guildId) {
		try {
			HashMap<String, Object> context = new HashMap<String, Object>();

			List<TemmieGuild> guilds = temmie.getUserGuilds();
			boolean allowed = false;
			for (TemmieGuild guild : guilds) {
				if (guild.getId().equals(guildId)) {
					allowed = LorittaWebsite.canManageGuild(guild);
					context.put("currentServer", guild);
					break;
				}
			}

			context.put("whereAmI", "idk");
			context.put("autoGeneratedModals", Arrays.asList("<h1>Erro!</h1>"));

			if (allowed) {
				PebbleTemplate template = null;
				ServerConfig sc = LorittaLauncher.getInstance().getServerConfigForGuild(guildId);
				context.put("serverConfig", sc);
				Map<CommandBase, CommandOptions> cmdOptions = new HashMap<>();

				for (CommandBase cmdBase : LorittaLauncher.getInstance().getCommandManager().getCommandMap()) {
					CommandOptions cmdOpti = sc.getCommandOptionsFor(cmdBase);
					cmdOptions.put(cmdBase, cmdOpti);
				}

				context.put("cmdOptions", cmdOptions);

				if (req.path().endsWith("commands")) {
					if (req.param("editingCommandOptions").isSet()) {
						String val = req.param("editingCommandOptions").value();
						for (CommandBase cmdBase : LorittaLauncher.getInstance().getCommandManager().getCommandMap()) {
							if (cmdBase.getClass().getSimpleName().equals(val)) {
								CommandOptions cmdOpti = sc.getCommandOptionsFor(cmdBase);

								for (Field f : cmdOpti.getClass().getFields()) {
									try {
										if (req.param(f.getName()).isSet()) {
											f.setBoolean(cmdOpti, true);
										} else {
											f.setBoolean(cmdOpti, false);
										}
									} catch (IllegalArgumentException | IllegalAccessException e) {
										e.printStackTrace();
									}
								}
								sc.commandOptions().put(cmdBase.getClass().getSimpleName(), cmdOpti);
								break;
							}
						}
					}
					if (req.param("editingCmds").isSet()) {
						ArrayList<String> enabledModules = new ArrayList<String>();
						for (CommandBase cmdBase : LorittaLauncher.getInstance().getCommandManager().getCommandMap()) {
							if (req.param(cmdBase.getClass().getSimpleName()).isSet()) {
								enabledModules.add(cmdBase.getClass().getSimpleName());
							}
						}
						sc.modules(enabledModules);
					}
					if (req.param("editingTristeRealidade").isSet()) {
						TristeRealidadeCommandOptions cmdOpti = new TristeRealidadeCommand.TristeRealidadeCommandOptions();
						cmdOpti.mentionEveryone(req.param("mentionEveryone").isSet());
						cmdOpti.hideDiscordTags(req.param("hideDiscordTags").isSet());
						sc.commandOptions().put("TristeRealidadeCommand", cmdOpti);
					}
					if (req.param("activateAllCommands").isSet()) {
						ArrayList<String> enabledModules = new ArrayList<String>();
						for (CommandBase cmdBase : LorittaLauncher.getInstance().getCommandManager().getCommandMap()) {
							enabledModules.add(cmdBase.getClass().getSimpleName());
						}
						sc.modules(enabledModules);
					}
					if (req.param("deactivateAllCommands").isSet()) {
						ArrayList<String> enabledModules = new ArrayList<String>();
						sc.modules(enabledModules);
					}
					LorittaLauncher.getInstance().getDs().save(sc);
					for (CommandBase cmdBase : LorittaLauncher.getInstance().getCommandManager().getCommandMap()) {
						context.put("commandOption" + cmdBase.getClass().getSimpleName(), new CommandOptions());
					}
					for (Entry<String, CommandOptions> entry : sc.commandOptions().entrySet()) {
						context.put("commandOption" + entry.getKey(), entry.getValue());
					}

					context.put("whereAmI", "moduleConfig");

					template = LorittaWebsite.engine.getTemplate("module_config.html");
					context.put("availableCmds", LorittaLauncher.getInstance().getCommandManager().getCommandMap());
					context.put("activeCmds", LorittaLauncher.getInstance().getCommandManager().getCommandsAvailableFor(sc));
				} else if (req.path().endsWith("joinconfig")) {
					if (req.param("enableModule").isSet()) { // O usuário está salvando as configurações?
						JoinLeaveConfig jlCnf = sc.joinLeaveConfig();
						jlCnf.setEnabled(req.param("enableModule").isSet());
						jlCnf.setTellOnJoin(req.param("tellOnJoin").isSet());
						jlCnf.setTellOnLeave(req.param("tellOnLeave").isSet());
						jlCnf.setCanalJoin(req.param("canalJoin").value());
						jlCnf.setCanalLeave(req.param("canalLeave").value());
						jlCnf.setJoinMessage(req.param("joinMessage").value());
						jlCnf.setLeaveMessage(req.param("leaveMessage").value());
	
						sc.joinLeaveConfig(jlCnf);
						LorittaLauncher.getInstance().getDs().save(sc);
					}
					context.put("whereAmI", "joinConfig");

					template = LorittaWebsite.engine.getTemplate("join_config.html");
				} else {
					if (req.param("commandPrefix").isSet()) {
						sc.commandPrefix(req.param("commandPrefix").value());
						LorittaLauncher.getInstance().getDs().save(sc);
					}

					if (req.param("commandMagic").isSet()) {
						sc.explainOnCommandRun(req.param("explainOnCommandRun").isSet());
						sc.mentionOnCommandOutput(req.param("mentionOnCommandOutput").isSet());
						sc.debugOptions().enableAllModules(req.param("enableAllModules").isSet());
						LorittaLauncher.getInstance().getDs().save(sc);
					}

					context.put("whereAmI", "mainPage");

					context.put("commandPrefix", sc.commandPrefix());
					template = LorittaWebsite.engine.getTemplate("server_config.html");
				}

				return new RenderWrapper(template, context);
			} else {
				try {
					res.redirect(LorittaWebsite.websiteUrl);
				} catch (Throwable e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		} catch (PebbleException e) {
			// TODO Auto-generated catch block
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			e.printStackTrace(pw);
			return e.toString();
		}
		return null;
	}
}