package net.perfectdreams.loritta.utils

enum class ActionType {
	UNKNOWN,

	UPDATE_GENERAL,
	UPDATE_MODERATION,
	UPDATE_COMMAND_LIST,
	UPDATE_PERMISSIONS,
	UPDATE_WELCOMER,
	UPDATE_EVENT_LOG,
	UPDATE_YOUTUBE,
	UPDATE_TWITCH,
	UPDATE_AUTOROLE,
	UPDATE_INVITE_BLOCK,
	UPDATE_MUSIC,
	UPDATE_ECONOMY,
	UPDATE_TIMERS,
	UPDATE_STARBOARD,
	UPDATE_MISCELLANEOUS,
	UPDATE_CUSTOM_BADGE,
	UPDATE_DAILY_MULTIPLIER,
	UPDATE_CUSTOM_COMMANDS,
	UPDATE_LEVEL_UP,
	UPDATE_TEXT_CHANNELS,
	UPDATE_PREMIUM,

	RESET_XP,

	UPDATE_TWITTER,
	UPDATE_RSS_FEEDS
}