package net.perfectdreams.loritta.api.platform

enum class PlatformFeature {
	ADD_LEFT_PAD,
	TYPING_STATUS,
	REACTIONS,
	RICH_EMBEDS,
	EMBED_LINKS,
	FILE_UPLOAD,
	IMAGE_UPLOAD,
	INLINE_KEYBOARD,
	SUPPORTS_MARKDOWN,
	SUPPORTS_HTML
}