package net.perfectdreams.loritta.common.utils

enum class TrackedChangeType {
    RESET_XP,

    CREATED_BLUESKY_TRACK,
    CHANGED_BLUESKY_TRACK,
    DELETED_BLUESKY_TRACK,

    CREATED_TWITCH_TRACK,
    EDITED_TWITCH_TRACK,
    DELETED_TWITCH_TRACK,

    CREATED_YOUTUBE_TRACK,
    CHANGED_YOUTUBE_TRACK,
    DELETED_YOUTUBE_TRACK,

    CREATED_CUSTOM_COMMAND,
    EDITED_CUSTOM_COMMAND,
    DELETED_CUSTOM_COMMAND,

    ACTIVATED_PREMIUM_KEY,
    DEACTIVATED_PREMIUM_KEY,

    CHANGED_AUTOROLE,
    CHANGED_CUSTOM_BADGE,
    CHANGED_CUSTOM_BADGE_IMAGE,
    CHANGED_BOM_DIA_E_CIA,
    CHANGED_COMMAND_CHANNELS,
    CHANGED_COMMANDS,
    CHANGED_DAILY_MULTIPLIER,
    CHANGED_DAILY_SHOP_TRINKETS,
    CHANGED_DROPS,
    CHANGED_EVENT_LOG,
    CHANGED_INVITE_BLOCKER,
    CHANGED_MEMBER_COUNTER,
    CHANGED_ROLE_PERMISSIONS,
    CHANGED_PREFIXED_COMMANDS,
    CHANGED_PUNISHMENT_LOG,
    CHANGED_QUIRKY_MODE,
    CHANGED_REACTION_EVENTS,
    CHANGED_STARBOARD,
    CHANGED_TAX_FREE_DAYS,
    CHANGED_WARN_ACTIONS,
    CHANGED_JOIN_LEAVE_MESSAGES,
    CHANGED_XP_BLOCKERS,
    CHANGED_XP_NOTIFICATIONS,
    CHANGED_XP_RATES,
    CHANGED_XP_REWARDS
}