package net.perfectdreams.loritta.website.backend

import net.perfectdreams.loritta.website.backend.utils.commands.AdditionalCommandInfoConfig

class LegacyLorittaCommands(val m: LorittaWebsiteBackend) {
    val additionalCommandsInfo = listOf(
        AdditionalCommandInfoConfig(
            "AmizadeCommand",
            m.images.commands.amizade
        ),
        AdditionalCommandInfoConfig(
            "AtaCommand",
            m.images.commands.ata
        ),
        AdditionalCommandInfoConfig(
            "AttackOnHeartCommand",
            videoUrl = "/loritta/commands/attack_on_heart.mp4"
        ),
        AdditionalCommandInfoConfig(
            "ArtCommand",
            m.images.commands.art
        ),
        AdditionalCommandInfoConfig(
            "AsciiCommand",
            m.images.commands.asciiArt
        ),
        AdditionalCommandInfoConfig(
            "AtendenteCommand",
            m.images.commands.atendente
        ),
        AdditionalCommandInfoConfig(
            "BobBurningPaperCommand",
            m.images.commands.bobFire
        ),
        AdditionalCommandInfoConfig(
            "BolsoDrakeCommand",
            m.images.commands.bolsoDrake
        ),
        AdditionalCommandInfoConfig(
            "BolsoFrameCommand",
            m.images.commands.bolsoFrame
        ),
        AdditionalCommandInfoConfig(
            "BolsonaroCommand",
            m.images.commands.bolsonaroTv
        ),
        AdditionalCommandInfoConfig(
            "Bolsonaro2Command",
            m.images.commands.bolsonaroTv2
        ),
        AdditionalCommandInfoConfig(
            "BriggsCoverCommand",
            m.images.commands.briggsCapa
        ),
        AdditionalCommandInfoConfig(
            "BuckShirtCommand",
            m.images.commands.buckShirt
        ),
        AdditionalCommandInfoConfig(
            "CanellaDvdCommand",
            m.images.commands.canellaDvd
        ),
        AdditionalCommandInfoConfig(
            "CepoCommand",
            m.images.commands.cepo
        ),
        AdditionalCommandInfoConfig(
            "CarlyAaahCommand",
            videoUrl = "/loritta/commands/carly_aaah.mp4"
        ),
        AdditionalCommandInfoConfig(
            "ChicoAtaCommand",
            m.images.commands.chicoAta
        ),
        AdditionalCommandInfoConfig(
            "CocieloChavesCommand",
            videoUrl = "/loritta/commands/cocielo_chaves.mp4"
        ),
        AdditionalCommandInfoConfig(
            "ContentAwareScaleCommand",
            m.images.commands.contentAwareScale
        ),
        AdditionalCommandInfoConfig(
            "CortesFlowCommand",
            imageUrl = "/loritta/commands/cortes_flow.jpg"
        ),
        AdditionalCommandInfoConfig(
            "DemonCommand",
            m.images.commands.demon
        ),
        AdditionalCommandInfoConfig(
            "DiscordiaCommand",
            m.images.commands.discordia
        ),
        AdditionalCommandInfoConfig(
            "DrakeCommand",
            m.images.commands.drake
        ),
        AdditionalCommandInfoConfig(
            "DrawnWordCommand",
            m.images.commands.drawnWord
        ),
        AdditionalCommandInfoConfig(
            "DrawnMaskCommand",
            m.images.commands.drawnMaskPlaca
        ),
        AdditionalCommandInfoConfig(
            "DeusCommand",
            m.images.commands.deus
        ),
        AdditionalCommandInfoConfig(
            "DeusesCommand",
            m.images.commands.deuses
        ),
        AdditionalCommandInfoConfig(
            "RipVidaCommand",
            m.images.commands.dogeVida
        ),
        AdditionalCommandInfoConfig(
            "EdnaldoBandeiraCommand",
            m.images.commands.ednaldoBandeira
        ),
        AdditionalCommandInfoConfig(
            "EdnaldoTvCommand",
            m.images.commands.ednaldoTv
        ),
        AdditionalCommandInfoConfig(
            "GangueCommand",
            m.images.commands.gangue
        ),
        AdditionalCommandInfoConfig(
            "GetOverHereCommand",
            m.images.commands.getOverHere
        ),
        AdditionalCommandInfoConfig(
            "GessyAtaCommand",
            m.images.commands.gessyAta
        ),
        AdditionalCommandInfoConfig(
            "GumballCommand",
            m.images.commands.gumball
        ),
        AdditionalCommandInfoConfig(
            "InverterCommand",
            m.images.commands.inverter
        ),
        AdditionalCommandInfoConfig(
            "JoojCommand",
            m.images.commands.jooj
        ),
        AdditionalCommandInfoConfig(
            "KnuxThrowCommand",
            m.images.commands.knuxThrow
        ),
        AdditionalCommandInfoConfig(
            "LavaCommand",
            m.images.commands.lava
        ),
        AdditionalCommandInfoConfig(
            "LavaReversoCommand",
            m.images.commands.lavaReverso
        ),
        AdditionalCommandInfoConfig(
            "LoriAtaCommand",
            m.images.commands.loriAta
        ),
        AdditionalCommandInfoConfig(
            "LoriSignCommand",
            m.images.commands.loriSign
        ),
        AdditionalCommandInfoConfig(
            "ManiaTitleCardCommand",
            m.images.commands.maniaTitleCard
        ),
        AdditionalCommandInfoConfig(
            "MorrePragaCommand",
            m.images.commands.morrePraga
        ),
        AdditionalCommandInfoConfig(
            "PassingPaperCommand",
            m.images.commands.passingPaper
        ),
        AdditionalCommandInfoConfig(
            "PerdaoCommand",
            m.images.commands.perdao
        ),
        AdditionalCommandInfoConfig(
            "PerfeitoCommand",
            m.images.commands.perfeito
        ),
        AdditionalCommandInfoConfig(
            "PepeDreamCommand",
            m.images.commands.pepeDream
        ),
        AdditionalCommandInfoConfig(
            "PetPetCommand",
            m.images.commands.petPet
        ),
        AdditionalCommandInfoConfig(
            "PrimeirasPalavrasCommand",
            m.images.commands.primeirasPalavras
        ),
        AdditionalCommandInfoConfig(
            "OjjoCommand",
            m.images.commands.ojjo
        ),
        AdditionalCommandInfoConfig(
            "QuadroCommand",
            m.images.commands.quadro
        ),
        AdditionalCommandInfoConfig(
            "RazoesCommand",
            m.images.commands.razoes
        ),
        AdditionalCommandInfoConfig(
            "RipTvCommand",
            m.images.commands.ripTv
        ),
        AdditionalCommandInfoConfig(
            "RomeroBrittoCommand",
            m.images.commands.romeroBritto
        ),
        AdditionalCommandInfoConfig(
            "SAMCommand",
            m.images.commands.sam
        ),
        AdditionalCommandInfoConfig(
            "SustoCommand",
            m.images.commands.susto
        ),
        AdditionalCommandInfoConfig(
            "StudiopolisTvCommand",
            m.images.commands.studiopolisTv
        ),
        AdditionalCommandInfoConfig(
            "SwingCommand",
            m.images.commands.swing
        ),
        AdditionalCommandInfoConfig(
            "TerminatorCommand",
            m.images.commands.terminator
        ),
        AdditionalCommandInfoConfig(
            "TriggeredCommand",
            m.images.commands.triggered
        ),
        AdditionalCommandInfoConfig(
            "TrumpCommand",
            m.images.commands.trump
        ),
        AdditionalCommandInfoConfig(
            "ToBeContinuedCommand",
            m.images.commands.toBeContinued
        )
    )
}