# This is a basic workflow to help you get started with Actions
name: Automatically merge Crowdin pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the cinnamon branch
on:
  pull_request:
    branches: [ cinnamon ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Automatically Merge Pull Request
      uses: sudo-bot/action-pull-request-merge@v1.1.0
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          allowed-usernames-regex: ^MrPowerGamerBR$
          merge-method: squash
          merge-title: "🤖 Automatically merge Crowdin updates 🌎"