name: Build Loritta Pull Request

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Get PR info
      run: echo ::set-env name=PR::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build Loritta
    - name: Build with Gradle
      run: "./gradlew build -Dbuild.number=$GITHUB_RUN_NUMBER -Dgit.branch=$GITHUB_REF -Dcommit.hash=$GITHUB_SHA -Dcompiled.at=${{ steps.current-time.outputs.time }}"

    # Upload Artifacts to GitHub
    # Loritta
    - uses: actions/upload-artifact@v2
      name: "Upload Loritta (Discord)"
      with:
        name: Loritta (Discord) [PR ${{ env.PR }}]
        path: loritta-discord/build/libs/loritta-discord-*.jar

    # Loritta Plugins
    - uses: actions/upload-artifact@v2
      name: "Upload Loritta (Plugins)"
      with:
        name: Loritta (Plugins) [PR ${{ env.PR }}]
        path: loritta-plugins/*/build/libs/*.jar

    # Spicy Morenitta
    - uses: actions/upload-artifact@v2
      name: "Upload Spicy Morenitta"
      with:
        name: Spicy Morenitta [PR ${{ env.PR }}]
        path: loritta-website/spicy-morenitta/build/web/*.js

    # Loritta Watchdog
    - uses: actions/upload-artifact@v2
      name: "Upload Loritta Watchdog"
      with:
        name: Loritta Watchdog [PR ${{ env.PR }}]
        path: loritta-watchdog-bot/build/libs/*.jar

    # Parallax Code Server
    - uses: actions/upload-artifact@v2
      name: "Upload Parallax Code Server"
      with:
        name: Parallax Code Server [PR ${{ env.PR }}]
        path: parallax-code-server/build/libs/*.jar

    # Shard Controller
    - uses: actions/upload-artifact@v2
      name: "Upload Shard Controller"
      with:
        name: Shard Controller [PR ${{ env.PR }}]
        path: shard-controller/build/libs/*.jar

    # Libs
    - uses: actions/upload-artifact@v2
      name: "Upload Loritta's Libs"
      with:
        name: Loritta (Libs) [PR ${{ env.PR }}]
        path: libs/*
