package net.perfectdreams.loritta.embededitor.utils

enum class MessageTagSection {
    MESSAGE_CONTENT,
    EMBED_PILL,
    EMBED_TITLE_NOT_NULL,
    EMBED_TITLE_NULL,
    EMBED_DESCRIPTION_NOT_NULL,
    EMBED_DESCRIPTION_NULL,
    EMBED_IMAGE_NOT_NULL,
    EMBED_IMAGE_NULL,
    EMBED_THUMBNAIL_NOT_NULL,
    EMBED_THUMBNAIL_NULL,
    EMBED_FOOTER_NOT_NULL,
    EMBED_FOOTER_NULL,
    EMBED_AUTHOR_NOT_NULL,
    EMBED_AUTHOR_NULL,
    EMBED_FIELDS_FIELD,
    EMBED_AFTER_FIELDS
}